// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfbymksromveyzphajfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYnlta3Nyb212ZXl6cGhhamZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTU2NTQsImV4cCI6MjA2MTU3MTY1NH0.mtYEFET5c8OAIjxxrFV3hqHss8QrCjLo4H0qHq9RjD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);